name: Packages

on:
  pull_request:

  push:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Type check
        run: yarn typedef
