name: Packages

on:
  pull_request:

  push:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v4
        width:
          node-version: 20.14.0

      - name: Install dependencies
        run: yarn install

      - name: Test packages
        run: yarn test

      - name: Lint packages
        run: yarn lint
